### ISSUE TITLE
Show pubkey together with IP and Port

### ISSUE THREAD

**Issue by bjarnemagnussen** [rawtxapp/rawtxapp#1]
I was trying to see the connection information for my rawtx wallet. When I click on "Receive" for the checking account and create an invoice, it does provide the pubkey. However, it does not provide the IP and Port which can be useful if the pubkey is not (yet?) broadcast to the public node graph and another wallet needs to connect to this node directly.

**Comment by rawtxapp** [comment]
Good idea, will implement it for the next release.

**Comment by bjarnemagnussen** [comment]
Great!

By the way, and maybe I am wrong on it because I am new to LND, but it looks like rawtx also does not advertise using its IP and Port? 

E.g. here is information on my rawtx node obtained by 1ML: https://1ml.com/testnet/node/0241ca44dc83e13149384b6141b17da5c5cab002244c8af7e65c33a7b0bd9b1156

But maybe this is on purpose because on a mobile phone the IP is expected to change a lot?

**Comment by rawtxapp** [comment]
It's on purpose because we don't want to route transactions on mobile (nodes will be down more often than up), so it would make the network worse if people had channels to mobile nodes (payments failing because route is down).

**Comment by bjarnemagnussen** [comment]
That sounds reasonable. Maybe just mention it in the Readme, so that noone will try to test this routing functionality?
