### ISSUE TITLE
Synced =true switch not flipped after completing 

### ISSUE THREAD

**Issue by OluAgunloye** [rawtxapp/rawtxapp#11]
@rawtxapp 
So I've just built from source for android studio SDK 28 
and using the prescribed LND patch and the syncing stops at 99% in the new app and never proceeds using the default wallet entered when creating a wallet. 

After closing the wallet, and trying to unlock the default wallet created above,  a notification appears letting me know that I need to upgrade the neutrino version of the default wallet, or I need to create a new wallet with the upgraded version of neutrino.

After upgrading to the new wallet, I see the the same behavior of not reaching beyond 99% synced.  
I'm using the latest .aar file!

EDIT: Just tried the new app download on iOS and the same result!  Will download it on Android and hopefully make it past syncing! 
Is what is happening related to a UI issue?  Meaning, does the block syncing occur via neutrino which is represented entirely by the syncing progress percentage, but the filter sync and the the Lightning Network sync happening in the background are NOT represented in the increase?

**Comment by OluAgunloye** [comment]
EDIT:

My hypothesis about he UI was correct.  You _must_ wait almost the full 10 min (8.75 min on average for me on emulator), _even_ if syncing has reached "99%".

**Comment by rawtxapp** [comment]
Sorry just saw this, yes, you're right, when it reaches 99%, it finished syncing block headers, it's starts syncing filter headers. There's a change in neutrino to do both of them in parallel, should be merged in soon and I'll update the bundled lnd to have it after testing it.
