### ISSUE TITLE
Pregenerate receiving onchain addresses

### ISSUE THREAD

**Issue by baryluk** [rawtxapp/rawtxapp#13]
I am not sure why but "Generate blockchain address" takes long time (about 10 seconds), and always results in different address.

Could you show derivation path under QR code after it is generated maybe?
And if it indeed is slow, how about generating in background few (or at least one) receiving address so getting new receiving address is instantaneous from the UI point of view? And once the app detects I got fund on this address, or viewed this address, immediately generate a new one in background for a next time.

**Comment by rawtxapp** [comment]
The NewAddressResponse only contains the address and not the derivation path, so it would need to be an lnd change. I can profile and see why it's slow, in general, it takes mine about a 1-2s. Are you running on iOS or Android ?

Caching might make sense, though again that would need to be done in lnd to avoid the state of the app being out of sync with lnd.
