### ISSUE TITLE
Native SegWit address (bech32)

### ISSUE THREAD

**Issue by baryluk** [rawtxapp/rawtxapp#14]
Hi,

would be nice if when receving on chain funds, I have an option to use native SegWit (bech32) address, instead of P2SH with compatibility encoding.

**Comment by rawtxapp** [comment]
Good idea, it should be relatively straightforward to implement. We just need to set the address type to p2wkh when calling NewAdress rpc.

Though I wonder what kind of UI is the most intuitive here. As in should we put 2 buttons, or a radio button, etc. Need to think a little bit more.

**Comment by Kixunil** [comment]
I like how Coinomi handles it.

![Address version selector in Coinomi](https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/29005818594/original/nzE1LAA01sjfO2DmBrj-lC_e-nQpkQ98jg.png?1522202614)
