### ISSUE TITLE
Interface does not scale: iOS: iPhone 4 

### ISSUE THREAD

**Issue by rstmsn** [rawtxapp/rawtxapp#15]
It is currently not possible to load an existing wallet when using an iPhone 4. The 'Unlock Wallet' button is clipping on the GUI.

![img_2417](https://user-images.githubusercontent.com/1072503/48378004-60b2a180-e6c7-11e8-8f52-55978edf96c3.PNG)

Again, when viewing the 'record seed' screen, the text is clipping at the top of the screen.

![img_2419 1](https://user-images.githubusercontent.com/1072503/48378032-77f18f00-e6c7-11e8-980b-672af1bd8690.PNG)

**Comment by rawtxapp** [comment]
Thanks for the detailed feedback with the screenshots, we'll get it fixed.

**Comment by rawtxapp** [comment]
The iOS version was removed. If it gets reintroduced, this should be fixed by then.
