### ISSUE TITLE
UI: 'Set password' failure notification text is illegible 

### ISSUE THREAD

**Issue by rstmsn** [rawtxapp/rawtxapp#16]
Setting a wallet password that does not meet the minimum password strength produces a notification: 'password must have at least 8 characters'. This message is barely legible on the iPhone 4. (White text on a light grey background).

![img_2420 1](https://user-images.githubusercontent.com/1072503/48378436-7c6a7780-e6c8-11e8-9327-909140300888.PNG)

**Comment by rawtxapp** [comment]
Good point, we'll change it.
