### ISSUE TITLE
Stuck on Syncing 99% 

### ISSUE THREAD

**Issue by kasadawa** [rawtxapp/rawtxapp#18]
OS : IOS 12  
Device: Iphone 7
Synced : 99% 

It's stuck on 99% and I've waited 2 hours. 
Do you still support/ develop this app ?

**Comment by rawtxapp** [comment]
hey @kasadawa, yes, it's still being developed. an upcoming version will fix this.

if you compile from the source with latest version of lnd, it should just work. if not, we just finished testing the last version and are waiting for app store approvals to release it.

**Comment by kasadawa** [comment]
Thanks for the fast reply.
I will wait for app store to approve it.

**Comment by rawtxapp** [comment]
fyi @kasadawa, it just got approved and we released it, might take a few hours to completely roll out on the app store. please try and let us know if you run into any issues. thanks for trying it!
