### ISSUE TITLE
Show more comprehensible status text

### ISSUE THREAD

**Issue by bjarnemagnussen** [rawtxapp/rawtxapp#3]
Here are a few thoughts I have on the status text after having used rawtx for a few days. 

Right now when creating a new wallet rawtx will first sync to the chain which is nicely shown in orange and updated information on how far it has synced already. But maybe a percentage display of how far it has currently synced could be added (even though strictly speaking as blocks can have different weight/sizes a calculation of percentage using the current number of synced blocks divided by the total number of blocks is only a rough estimate of the percentage).

After rawtx is synced with the blockchain it shows in green that it is fully synced to the chain. Then rawtx will build up the lightning network graph and therefore also show in orange the text that it is syncing with the lightning network.

But at first I did not catch the subtly different text (Syncing to the chain vs Syncing with lightning network) and therefore thought that it was now fully synced and ready to be used and the text in orange just a bug/leftover. 

Building up the network graph can take many hours and so I already opened a channel but afterwards realised that only few routes if any were possible for payments. Knowing how it works now, I easily understand the messages, but the first time I did not catch the differences. Therefore I think it would be good to make it even more clear.

Maybe instead of showing synced to the chain in green immediately after having synced to the blockchain, rawtx could then say "Building the lighting network graph" or something similarly distinct from the syncing-to-the-chain message and wait until it is both synced to the chain and has build up the network graph to show that it is fully synced in green? Maybe rawtx could also block the possibilities of paying/receiving invoices with a notice to wait until synced with the lightning network when the user tries it before, or at least show this message when trying to pay/receive invoices as long as the network graph is still being build?

Just my 2 cents.

**Comment by rawtxapp** [comment]
Makes sense, thanks for the detailed feedback. Will change the message to be more intuitive and show warning/block when trying send and receive payments.

Currently working on improving the network sync time, for the initial sync, it should take less than 30 minutes very soon instead of hours and eventually want to bring it to less than 10min.

**Comment by rawtxapp** [comment]
Closing this one for now as it will be obsolete in the next release of the wallet which will be available shortly after lnd 0.5 release is official.
