### ISSUE TITLE
QR Code functionality for Android

### ISSUE THREAD

**Issue by OluAgunloye** [rawtxapp/rawtxapp#6]
Not sure if this should go in an issue or if there is a page for feature request inquiries, but do you have native Android QR support or do you use API's to accomplish this task?

Is there Android QR support or a plan for this  (couldn't see it in the code, but that might just be me)?

**Comment by rawtxapp** [comment]
There's a QR code scanner, here's how it's used: https://github.com/rawtxapp/rawtxapp/blob/ba4e23499f22beadec04acd66e266c6d9848c8fa/NativeRtxModule.js#L71. It is implemented using Java on Android and objC on iOS.
